Repository whateverusername0/Goob-Station, pull requests merged in 2025-02, with the labels that each got.

#17 hierophant fix
  Content.Server/_Lavaland/Mobs/Hierophant/HierophantChaserSystem.cs
Labels: S: Untriaged, size/S

#18 Survival Medipen
  Resources/Prototypes/_Lavaland/Entities/Objects/Specific/Medical/hypospray.yml
  Resources/Prototypes/_Lavaland/Reagents/medicine.yml
  Resources/Textures/_Lavaland/Objects/Specific/Medical/medipen.rsi/meta.json
  Resources/Textures/_Lavaland/Objects/Specific/Medical/medipen.rsi/survivalpen.png
  Resources/Textures/_Lavaland/Objects/Specific/Medical/medipen.rsi/survivalpen_empty.png
Labels: Changes: Sprites, Changes: Map, S: Untriaged, Changes: No C#, size/S, S: Needs Review

#19 Small refactor to PKA mod system
  Content.Shared/_Lavaland/CCVar/CCVars.Lavaland.cs
  Content.Shared/_Lavaland/Weapons/Ranged/Upgrades/Components/GunComponentUpdateComponent.cs
  Content.Shared/_Lavaland/Weapons/Ranged/Upgrades/Components/GunUpgradeComponent.cs
  Content.Shared/_Lavaland/Weapons/Ranged/Upgrades/Components/UpgradeableGunComponent.cs
  Content.Shared/_Lavaland/Weapons/Ranged/Upgrades/GunUpgradeSystem.cs
  Resources/Locale/en-US/_Lavaland/prototypes/Entities/Objects/Specific/gun_upgrades.ftl
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Basic/base_pka.yml
  Resources/Prototypes/_Lavaland/Entities/Objects/Weapons/pka_upgrade.yml
Labels: S: Untriaged, size/M

#21 DAMNATION
  Resources/Prototypes/_Goobstation/ore.yml
  Resources/Prototypes/ore.yml
Labels: S: Untriaged, Changes: No C#, size/S
